version: '3.7'
services:
  splunk:
    container_name: splunk
    image: splunk/splunk:latest
    volumes:
      - ./splunk/SplunkForwarder/default:/opt/splunk/etc/apps/SplunkForwarder/default
    ports:
      - 8000:8000
      - 8088-8089:8088-8089
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=E7NK_6W*m_elWtPd