version: '3.7'
services:
  splunk:
    container_name: splunk_forwarder
    image: splunk/splunk:latest
    volumes:
      - ./splunk/outputs.conf:/opt/splunk/etc/system/local/outputs.conf
    ports:
      - 8000:8000
      - 8088-8089:8088-8089
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=E7NK_6W*m_elWtPd